---
title: "R Packages"
#author: "Stefan Schmidt"
#date: "7/29/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Notes taken while reading Haley Wickham's _R Packages_ book 2nd edition which
can be read online [here](https://r-pkgs.org/).

## Chapter 1 -- Introduction

* get help on a package using `package?<pkg-name>` or
`help(package="<pkg-name>")`
* 10 developers at RStudio maintain 150 open source R packages
* vignettes - long-form documents that show how to combine multiple parts of
your package to solve real problems
* `R/` directory is for your R code, while `src/` is for C and C++ code
* 


## Chapter 2 -- Overview

### Development Process

* `usethis::create_package("~/path/to/pkg-name")` - creates new package project
from template.
* `usethis::use_git()` - initializes git and offers initial commit.
* `usethis::use_r("fct-name")` - create template for your first function.
* `devtools::load_all()` - load the complete package.
* test and commit your changes.
* `devtools::check()` - runs 50 different checks (background: R CMD check).
* `usethis::use_build_ignore()` - adds files to `.Rbuildignore` (files needed
during development, but not part of deployment).
* `usethis::use_mit_licence("user-name")` - creates MIT licence for user (same
available for GPL, Apache).
* insert roxygen skeleton (Ctrl + Shift + Alt + R) - creates documentation
skeleton.
* `devtools::document()` - generates man pages for functions with edited
roxygen2 skeleton.
* `devtools::install()` - installs package (RStudio: Shift + Cmd + B).
* `usethis::use_testthat()` - 



## R packages needed for Development

* devtools - swiss army knife for package development
* usethis - package development tools (dependency of devtools)
* roxygen2 - documentation of your functions
* rmarkdown - create e.g. vignettes
* knitr - documentation weaving
* testthat - unit test suite
* desc - 
* pkgbuild - 
* pkgload - 
* rcmdcheck - 
* remotes - 
* revdepcheck - 
* sessioninfo - 
* fs - file system work




